name: sweets-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - wget # ASF Downloading
  # - isce3>=0.14.0
  # - compass>=0.4.1
  # - dask>=2022.6.0
  # - dolphin>=0.2.0
  # - gdal>=3.5
  # - h5py>=3.6
  # - numpy>=1.20
  # - opera-utils>=0.1.1
  # - pydantic>=2.1
  # - requests>=2.20
  # - rich>=12.0
  # - rioxarray>=0.13
  # - s1reader>=0.2.1
  # - sardem>=0.11.3
  # - sentineleof>=0.7.0
  # - shapely>=1.8
  - isce3>=0.14.0
  - compass>=0.4.1
  - dask
  - dolphin>=0.5.1
  - gdal
  - h5py
  - numpy
  - opera-utils
  - pydantic>2.1
  - pyproj>=3.3
  - python-dateutil
  - rasterio
  - requests
  - rich
  - rioxarray
  - sardem
  - sentineleof>=0.9.5
  - shapely
