name: sweets-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.3
  - git
  - wget
  - isce3>=0.14.0
  - colorcet
  - compass>=0.4.1
  - dask
  - dolphin>=0.5.1
  - gdal
  - h5py
  - numpy
  - opera-utils
  - pydantic>2.1
  - pyproj>=3.3
  - python-dateutil
  - rasterio
  - requests
  - rich
  - rioxarray
  - sardem
  - sentineleof
  - shapely
